name: simple_image_crop
description: A simple and easy to use flutter plugin to crop image on iOS and Android.
version: 1.0.1
homepage: https://github.com/yoni1988/flutter_simple_image_crop.git

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.simpleimagecrop
        pluginClass: SimpleImageCropPlugin
      ios:
        pluginClass: SimpleImageCropPlugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.0"
